/**
 * CyberSport Portal
 * Документация REST API
 *
 * OpenAPI spec version: 1.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface CreateGameDto {
  /**
   * Название игры (дисциплины)
   */
  title: string;
  /**
   * Короткое название
   */
  shortTitle: string;
  /**
   * Описание дисциплины (игры)
   */
  description: string;
  /**
   * Жанр дисциплины (игры)
   */
  genre: string;
  /**
   * URL игры в магазине
   */
  storeUrl: string;
  /**
   * URL фото игры
   */
  mainImageUrl: string;
  /**
   * URL бэкграунда игры
   */
  backgroundImageUrl: string;
}
