/**
 * CyberSport Portal
 * Документация REST API
 *
 * OpenAPI spec version: 1.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Event {
  /**
   * Уникальный id
   */
  id: number;
  /**
   * Название события
   */
  title: string;
  /**
   * Описание события
   */
  description: string;
  /**
   * Дата и время начала события
   */
  start: string;
  /**
   * Дата и время конца события
   */
  end: string;
  /**
   * Место проведения
   */
  location: string;
  /**
   * URL фото
   */
  mainImageUrl: string;
  /**
   * id привязанного университета
   */
  universityId: number;
  /**
   * id пользователя
   */
  userId: number;
  /**
   * id игры
   */
  gameId: number;
}
