/**
 * CyberSport Portal
 * Документация REST API
 *
 * OpenAPI spec version: 1.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Team {
  /**
   * Уникальный id
   */
  id: number;
  /**
   * Название команды
   */
  title: string;
  /**
   * Описание команды
   */
  description: string;
  /**
   * url, по которому можно получить лого
   */
  logoUrl: string;
  /**
   * Тип команды
   */
  teamType: string;
  /**
   * Количество участников команды
   */
  membersCount: number;
  /**
   * id капитана команды
   */
  captainId: number;
  /**
   * id игры
   */
  gameId: number;
  /**
   * id привязанного университета
   */
  universityId: number;
}
