/**
 * CyberSport Portal
 * Документация REST API
 *
 * OpenAPI spec version: 1.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface University {
  /**
   * Уникальный id университета
   */
  id: number;
  /**
   * Название университета
   */
  title: string;
  /**
   * Краткое название университета
   */
  shortName: string;
  /**
   * E-mail университета
   */
  email: string;
  /**
   * Номер университета
   */
  phone: string;
  /**
   * url главного сайта университета
   */
  link: string;
  /**
   * url, по которому можно получить лого
   */
  logoUrl: string;
  /**
   * Адрес университета
   */
  address: string;
}
