/**
 * CyberSport Portal
 * Документация REST API
 *
 * OpenAPI spec version: 1.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface UpdateUserDto {
  /**
   * Почта
   */
  email?: string;
  /**
   * Логин
   */
  login?: string;
  /**
   * Мобильный номер пользователя
   */
  phone?: string;
  /**
   * Дата рождения пользователя
   */
  birthDate?: Date;
  /**
   * пароль
   */
  password?: string;
  /**
   * имя
   */
  firstName?: string;
  /**
   * отчество
   */
  patronymic?: string;
  /**
   * фамилия
   */
  lastName?: string;
  /**
   * url, по которому можно получить фото
   */
  photoUrl?: string;
  /**
   * О себе
   */
  aboutYourself?: string;
  /**
   * Пол (male / female)
   */
  gender?: string;
  /**
   * Студенческий билет
   */
  studentCard?: string;
  /**
   * Id университета
   */
  universityId?: number;
  /**
   * Статус пользователя
   */
  status: string;
  /**
   * В сети
   */
  isOnline: boolean;
  /**
   * Был в сети
   */
  lastOnline: Date;
  /**
   * Причина блокировки
   */
  blockReason: string;
  /**
   * Дата и время начала блокровки
   */
  bannedFromDate: string;
  /**
   * Дата и время окончания блокировки
   */
  bannedToDate: string;
  /**
   * id привязанного к модератору университета
   */
  moderatedUniversityId: number;
}
