/**
 * CyberSport Portal
 * Документация REST API
 *
 * OpenAPI spec version: 1.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface UpdateTeamDto {
  /**
   * Название команды
   */
  title?: string;
  /**
   * Описание команды
   */
  description?: string;
  /**
   * Количество участников команды
   */
  membersCount?: number;
  /**
   * url, по которому можно получить лого
   */
  logoUrl?: string;
  /**
   * Тип команды
   */
  teamType?: string;
  /**
   * Уникальный идентификатор капитана команды
   */
  captainId?: number;
  /**
   * Уникальный идентификатор дисциплины (игры) команды
   */
  gameId?: number;
  /**
   * id привязанного университета
   */
  universityId?: number;
}
