/**
 * CyberSport Portal
 * Документация REST API
 *
 * OpenAPI spec version: 1.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface User {
  /**
   * Уникальный id
   */
  id: number;
  /**
   * E-mail
   */
  email: string;
  /**
   * Логин
   */
  login: string;
  /**
   * Мобильный номер пользователя
   */
  phone: string;
  /**
   * Уровень пользователя
   */
  level: number;
  /**
   * Кол-во очков
   */
  points: number;
  /**
   * Пароль
   */
  password: string;
  /**
   * Статус пользователя
   */
  status: string;
  /**
   * Пользователь в сети
   */
  isOnline: string;
  /**
   * Последний раз в сети
   */
  lastOnline: Date;
  /**
   * Имя
   */
  firstName: string;
  /**
   * Фамилия
   */
  lastName: string;
  /**
   * Отчество
   */
  patronymic: string;
  /**
   * Пол
   */
  gender: string;
  /**
   * Дата рождения
   */
  birthDate: string;
  /**
   * О себе
   */
  aboutYourself: string;
  /**
   * Номер студенческого
   */
  studentCard: string;
  /**
   * url, по которому можно получить фото
   */
  photoUrl: string;
  /**
   * Причина блокировки
   */
  blockReason: string;
  /**
   * Дата и время начала блокировки
   */
  bannedFromDate: string;
  /**
   * Дата и время окончания блокировки
   */
  bannedToDate: string;
  /**
   * id университета, в котором пользователь обучается
   */
  universityId: number;
  /**
   * id привязанного к модератору университета
   */
  moderatedUniversityId: number;
}
